import unittest
import pykicadlib.symbol.element


class TestSymbolElementFromStrField(unittest.TestCase):
    def test_parser(self):
        test = pykicadlib.symbol.element.from_str('F1 "Text" 10 20 50 H V C CNN "Name"')
        self.assertIsInstance(test, pykicadlib.symbol.element.field)
        self.assertEqual(test.type, pykicadlib.symbol.type.field.name)
        self.assertEqual(test.value, 'Text')
        self.assertEqual(test.x, 10)
        self.assertEqual(test.y, 20)
        self.assertEqual(test.size, 50)
        self.assertEqual(test.orientation, pykicadlib.symbol.type.orientation.horizontal)
        self.assertEqual(test.visibility, pykicadlib.symbol.type.visibility.visible)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.center)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.center)
        self.assertEqual(test.style, pykicadlib.symbol.type.style.none)


class TestSymbolElementFromStrPolygon(unittest.TestCase):
    def test_parser(self):
        test = pykicadlib.symbol.element.from_str('P 3 0 1 0 -50 50 50 0 -50 -50 F')
        self.assertIsInstance(test, pykicadlib.symbol.element.polygon)
        self.assertEqual(len(test.points), 3)
        self.assertEqual(str(test.points[0]), '-50 50')
        self.assertEqual(str(test.points[1]), '50 0')
        self.assertEqual(str(test.points[2]), '-50 -50')
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.fill, pykicadlib.symbol.type.fill.foreground)

        test = pykicadlib.symbol.element.from_str('P 2 0 1 0 50 50 50 -50 N')
        self.assertIsInstance(test, pykicadlib.symbol.element.polygon)
        self.assertEqual(len(test.points), 2)
        self.assertEqual(str(test.points[0]), '50 50')
        self.assertEqual(str(test.points[1]), '50 -50')
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.fill, pykicadlib.symbol.type.fill.none)


class TestSymbolElementFromStrRectangle(unittest.TestCase):
    def test_parser(self):
        test = pykicadlib.symbol.element.from_str('S 0 50 900 900 0 1 0 f')
        self.assertIsInstance(test, pykicadlib.symbol.element.rectangle)
        self.assertEqual(test.x1, 0)
        self.assertEqual(test.y1, 50)
        self.assertEqual(test.x2, 900)
        self.assertEqual(test.y2, 900)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.thickness, 0)
        self.assertEqual(test.fill, pykicadlib.symbol.type.fill.background)


class TestSymbolElementFromStrCirlce(unittest.TestCase):
    def test_parser(self):
        test = pykicadlib.symbol.element.from_str('C 10 20 70 2 1 5 F')
        self.assertIsInstance(test, pykicadlib.symbol.element.circle)
        self.assertEqual(test.x, 10)
        self.assertEqual(test.y, 20)
        self.assertEqual(test.radius, 70)
        self.assertEqual(test.unit, 2)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.thickness, 5)
        self.assertEqual(test.fill, pykicadlib.symbol.type.fill.foreground)

        test = pykicadlib.symbol.element.from_str('C 0 0 20 0 1 0 N')
        self.assertIsInstance(test, pykicadlib.symbol.element.circle)
        self.assertEqual(test.x, 0)
        self.assertEqual(test.y, 0)
        self.assertEqual(test.radius, 20)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.thickness, 0)
        self.assertEqual(test.fill, pykicadlib.symbol.type.fill.none)


class TestSymbolElementFromStrArc(unittest.TestCase):
    def test_parser(self):
        test = pykicadlib.symbol.element.from_str('A -1 -200 49 900 -11 0 1 0 N -50 -200 0 -150')
        self.assertIsInstance(test, pykicadlib.symbol.element.arc)
        self.assertEqual(test.x, -1)
        self.assertEqual(test.y, -200)
        self.assertEqual(test.radius, 49)
        self.assertEqual(test.startAngle, 90.0)
        self.assertEqual(test.endAngle, -1.1)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.thickness, 0)
        self.assertEqual(test.fill, pykicadlib.symbol.type.fill.none)
        self.assertEqual(test.startX, -50)
        self.assertEqual(test.startY, -200)
        self.assertEqual(test.endX, 0)
        self.assertEqual(test.endY, -150)

        test = pykicadlib.symbol.element.from_str('A 0 -199 49 0 -911 0 1 0 N 0 -150 50 -200')
        self.assertIsInstance(test, pykicadlib.symbol.element.arc)
        self.assertEqual(test.x, 0)
        self.assertEqual(test.y, -199)
        self.assertEqual(test.radius, 49)
        self.assertEqual(test.startAngle, 0.0)
        self.assertEqual(test.endAngle, -91.1)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.thickness, 0)
        self.assertEqual(test.fill, pykicadlib.symbol.type.fill.none)
        self.assertEqual(test.startX, 0)
        self.assertEqual(test.startY, -150)
        self.assertEqual(test.endX, 50)
        self.assertEqual(test.endY, -200)


class TestSymbolElementFromStrText(unittest.TestCase):
    def test_old_format_parser(self):
        # Old format
        test = pykicadlib.symbol.element.from_str('T 0 -320 -10 100 0 0 1 VREF')
        self.assertIsInstance(test, pykicadlib.symbol.element.text)
        self.assertEqual(test.x, -320)
        self.assertEqual(test.y, -10)
        self.assertEqual(test.value, 'VREF')
        self.assertEqual(test.size, 100)
        self.assertEqual(test.angle, 0.0)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.italic, pykicadlib.symbol.type.italic.off)
        self.assertEqual(test.bold, pykicadlib.symbol.type.bold.off)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.center)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.center)

        test = pykicadlib.symbol.element.from_str('T 1 20 10 50 0 2 0 TEXT~SPACE')
        self.assertIsInstance(test, pykicadlib.symbol.element.text)
        self.assertEqual(test.x, 20)
        self.assertEqual(test.y, 10)
        self.assertEqual(test.value, 'TEXT SPACE')
        self.assertEqual(test.size, 50)
        self.assertEqual(test.angle, 90.0)
        self.assertEqual(test.unit, 2)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.both)
        self.assertEqual(test.italic, pykicadlib.symbol.type.italic.off)
        self.assertEqual(test.bold, pykicadlib.symbol.type.bold.off)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.center)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.center)

    def test_new_format_parser(self):
        # New format
        test = pykicadlib.symbol.element.from_str('T 0 200 100 50 0 0 1 "Text with space" Normal 0 C C')
        self.assertIsInstance(test, pykicadlib.symbol.element.text)
        self.assertEqual(test.x, 200)
        self.assertEqual(test.y, 100)
        self.assertEqual(test.value, 'Text with space')
        self.assertEqual(test.size, 50)
        self.assertEqual(test.angle, 0.0)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.italic, pykicadlib.symbol.type.italic.off)
        self.assertEqual(test.bold, pykicadlib.symbol.type.bold.off)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.center)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.center)

        test = pykicadlib.symbol.element.from_str('T 450 10 20 50 0 0 1 "A\'\'B" Normal 0 C C')
        self.assertIsInstance(test, pykicadlib.symbol.element.text)
        self.assertEqual(test.x, 10)
        self.assertEqual(test.y, 20)
        self.assertEqual(test.value, 'A"B')
        self.assertEqual(test.size, 50)
        self.assertEqual(test.angle, 45.0)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.italic, pykicadlib.symbol.type.italic.off)
        self.assertEqual(test.bold, pykicadlib.symbol.type.bold.off)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.center)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.center)

        test = pykicadlib.symbol.element.from_str('T 450 10 20 50 0 0 1 "Test" Normal 0 L T')
        self.assertIsInstance(test, pykicadlib.symbol.element.text)
        self.assertEqual(test.x, 10)
        self.assertEqual(test.y, 20)
        self.assertEqual(test.value, 'Test')
        self.assertEqual(test.size, 50)
        self.assertEqual(test.angle, 45.0)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.italic, pykicadlib.symbol.type.italic.off)
        self.assertEqual(test.bold, pykicadlib.symbol.type.bold.off)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.left)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.top)

        test = pykicadlib.symbol.element.from_str('T 450 10 20 50 0 0 1 "Test" Normal 0 R B')
        self.assertIsInstance(test, pykicadlib.symbol.element.text)
        self.assertEqual(test.x, 10)
        self.assertEqual(test.y, 20)
        self.assertEqual(test.value, 'Test')
        self.assertEqual(test.size, 50)
        self.assertEqual(test.angle, 45.0)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.italic, pykicadlib.symbol.type.italic.off)
        self.assertEqual(test.bold, pykicadlib.symbol.type.bold.off)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.right)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.bottom)

        test = pykicadlib.symbol.element.from_str('T 450 10 20 50 0 0 1 "Test" Italic 1 C C')
        self.assertIsInstance(test, pykicadlib.symbol.element.text)
        self.assertEqual(test.x, 10)
        self.assertEqual(test.y, 20)
        self.assertEqual(test.value, 'Test')
        self.assertEqual(test.size, 50)
        self.assertEqual(test.angle, 45.0)
        self.assertEqual(test.unit, 0)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.italic, pykicadlib.symbol.type.italic.on)
        self.assertEqual(test.bold, pykicadlib.symbol.type.bold.on)
        self.assertEqual(test.hjustify, pykicadlib.symbol.type.hjustify.center)
        self.assertEqual(test.vjustify, pykicadlib.symbol.type.vjustify.center)


class TestSymbolElementFromStrPin(unittest.TestCase):
    def test_pin(self):
        test = pykicadlib.symbol.element.from_str('X TO 1 -200 0 150 R 40 40 1 1 P')
        self.assertIsInstance(test, pykicadlib.symbol.element.pin)
        self.assertEqual(test.x, -200)
        self.assertEqual(test.y, 0)
        self.assertEqual(test.name, 'TO')
        self.assertEqual(test.number, '1')
        self.assertEqual(test.length, 150)
        self.assertEqual(test.direction, pykicadlib.symbol.type.direction.left)
        self.assertEqual(test.nameSize, 40)
        self.assertEqual(test.numberSize, 40)
        self.assertEqual(test.unit, 1)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.electric, pykicadlib.symbol.type.electric.passive)
        self.assertEqual(test.shape, pykicadlib.symbol.type.shape.line)
        self.assertTrue(test.visible)

        test = pykicadlib.symbol.element.from_str('X K 2 200 0 150 L 40 40 1 1 P')
        self.assertIsInstance(test, pykicadlib.symbol.element.pin)
        self.assertEqual(test.x, 200)
        self.assertEqual(test.y, 0)
        self.assertEqual(test.name, 'K')
        self.assertEqual(test.number, '2')
        self.assertEqual(test.length, 150)
        self.assertEqual(test.direction, pykicadlib.symbol.type.direction.right)
        self.assertEqual(test.nameSize, 40)
        self.assertEqual(test.numberSize, 40)
        self.assertEqual(test.unit, 1)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.electric, pykicadlib.symbol.type.electric.passive)
        self.assertEqual(test.shape, pykicadlib.symbol.type.shape.line)
        self.assertTrue(test.visible)

        test = pykicadlib.symbol.element.from_str('X 0 1 0 0 0 R 40 40 1 1 W NC')
        self.assertIsInstance(test, pykicadlib.symbol.element.pin)
        self.assertEqual(test.x, 0)
        self.assertEqual(test.y, 0)
        self.assertEqual(test.name, '0')
        self.assertEqual(test.number, '1')
        self.assertEqual(test.length, 0)
        self.assertEqual(test.direction, pykicadlib.symbol.type.direction.left)
        self.assertEqual(test.nameSize, 40)
        self.assertEqual(test.numberSize, 40)
        self.assertEqual(test.unit, 1)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.electric, pykicadlib.symbol.type.electric.power_input)
        self.assertEqual(test.shape, pykicadlib.symbol.type.shape.clock)
        self.assertFalse(test.visible)

        test = pykicadlib.symbol.element.from_str('X ~ 2 0 -250 200 U 40 40 1 1 P')
        self.assertIsInstance(test, pykicadlib.symbol.element.pin)
        self.assertEqual(test.x, 0)
        self.assertEqual(test.y, -250)
        self.assertEqual(test.name, '~')
        self.assertEqual(test.number, '2')
        self.assertEqual(test.length, 200)
        self.assertEqual(test.direction, pykicadlib.symbol.type.direction.down)
        self.assertEqual(test.nameSize, 40)
        self.assertEqual(test.numberSize, 40)
        self.assertEqual(test.unit, 1)
        self.assertEqual(test.representation, pykicadlib.symbol.type.representation.normal)
        self.assertEqual(test.electric, pykicadlib.symbol.type.electric.passive)
        self.assertEqual(test.shape, pykicadlib.symbol.type.shape.line)
        self.assertTrue(test.visible)

    def test_exception(self):
        with self.assertRaises(KeyError):
            pykicadlib.symbol.element.from_str('Z')
